export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_ERROR = 'SIGNIN_USER_ERROR';
export const SIGNOUT_USER = 'SIGNOUT_USER';
export const CLEAR_ERROR= 'CLEAR_ERROR';
export const SET_USER_PROFILE  = 'SET_USER_PROFILE';
export const GET_ENTRIES ='GET_ENTRIES' ;

